CC = gcc
CXX = g++

INCLUDES = -I../../cs3157/lab3/solutions/part1
CFLAGS = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES)

LDFLAGS = -g -L../../cs3157/lab3/solutions/part1
LDLIBS = -lmylist

.PHONY: default
default: mdb-add mdb-lookup

mdb-lookup: mdb.o

mdb-add: mdb.o

mdb-add.o: mdb.h

mdb-lookup.o: mdb.h

mdb.o: mdb.h

./PHONY: clean
clean: 
	rm -f *.o *~ a.out core mdb-add mdb-lookup

.PHONY: all
all: clean default
